theme: jekyll-theme-slate
lang: pt-PT
title: BATIC - Braille aplicado às TIC
description: um subgrupo do <strong>Núcleo para o Braille e Meios Complementares de Leitura</strong>
show_downloads: false
