theme: jekyll-theme-slate
lang: pt-PT
title: BATIC
description: Braille aplicado às TIC - subgrupo do Núcleo Braille e Meios Complementares de Leitura
show_downloads: false
github:
  is_project_page: false
